// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0
// source: property.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const checkPropertyOwnerShip = `-- name: CheckPropertyOwnerShip :one
SELECT count(*) FROM properties WHERE id = $1 AND owner_id = $2 LIMIT 1
`

type CheckPropertyOwnerShipParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) CheckPropertyOwnerShip(ctx context.Context, arg CheckPropertyOwnerShipParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkPropertyOwnerShip, arg.ID, arg.OwnerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProperty = `-- name: CreateProperty :one
INSERT INTO properties (
  owner_id,
  name,
  area,
  number_of_floors,
  year_built,
  orientation,
  full_address,
  district,
  city,
  lat,
  lng,
  type,
  created_at,
  updated_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  NOW(),
  NOW()
) RETURNING id, owner_id, name, area, number_of_floors, year_built, orientation, full_address, district, city, lat, lng, type, created_at, updated_at
`

type CreatePropertyParams struct {
	OwnerID        uuid.UUID      `json:"owner_id"`
	Name           sql.NullString `json:"name"`
	Area           float32        `json:"area"`
	NumberOfFloors sql.NullInt32  `json:"number_of_floors"`
	YearBuilt      sql.NullInt32  `json:"year_built"`
	Orientation    sql.NullString `json:"orientation"`
	FullAddress    string         `json:"full_address"`
	District       string         `json:"district"`
	City           string         `json:"city"`
	Lat            float64        `json:"lat"`
	Lng            float64        `json:"lng"`
	Type           PROPERTYTYPE   `json:"type"`
}

func (q *Queries) CreateProperty(ctx context.Context, arg CreatePropertyParams) (Property, error) {
	row := q.db.QueryRowContext(ctx, createProperty,
		arg.OwnerID,
		arg.Name,
		arg.Area,
		arg.NumberOfFloors,
		arg.YearBuilt,
		arg.Orientation,
		arg.FullAddress,
		arg.District,
		arg.City,
		arg.Lat,
		arg.Lng,
		arg.Type,
	)
	var i Property
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Area,
		&i.NumberOfFloors,
		&i.YearBuilt,
		&i.Orientation,
		&i.FullAddress,
		&i.District,
		&i.City,
		&i.Lat,
		&i.Lng,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPropertyAmenity = `-- name: CreatePropertyAmenity :one
INSERT INTO property_amenity (
  property_id,
  amenity_id,
  description
) VALUES (
  $1,
  $2,
  $3
) RETURNING property_id, amenity_id, description
`

type CreatePropertyAmenityParams struct {
	PropertyID  uuid.UUID      `json:"property_id"`
	AmenityID   int64          `json:"amenity_id"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreatePropertyAmenity(ctx context.Context, arg CreatePropertyAmenityParams) (PropertyAmenity, error) {
	row := q.db.QueryRowContext(ctx, createPropertyAmenity, arg.PropertyID, arg.AmenityID, arg.Description)
	var i PropertyAmenity
	err := row.Scan(&i.PropertyID, &i.AmenityID, &i.Description)
	return i, err
}

const createPropertyFeature = `-- name: CreatePropertyFeature :one
INSERT INTO property_feature (
  property_id,
  feature_id,
  description
) VALUES (
  $1,
  $2,
  $3
) RETURNING property_id, feature_id, description
`

type CreatePropertyFeatureParams struct {
	PropertyID  uuid.UUID      `json:"property_id"`
	FeatureID   int64          `json:"feature_id"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreatePropertyFeature(ctx context.Context, arg CreatePropertyFeatureParams) (PropertyFeature, error) {
	row := q.db.QueryRowContext(ctx, createPropertyFeature, arg.PropertyID, arg.FeatureID, arg.Description)
	var i PropertyFeature
	err := row.Scan(&i.PropertyID, &i.FeatureID, &i.Description)
	return i, err
}

const createPropertyMedia = `-- name: CreatePropertyMedia :one
INSERT INTO property_media (
  property_id,
  url,
  type
) VALUES (
  $1,
  $2,
  $3
) RETURNING id, property_id, url, type
`

type CreatePropertyMediaParams struct {
	PropertyID uuid.UUID `json:"property_id"`
	Url        string    `json:"url"`
	Type       MEDIATYPE `json:"type"`
}

func (q *Queries) CreatePropertyMedia(ctx context.Context, arg CreatePropertyMediaParams) (PropertyMedium, error) {
	row := q.db.QueryRowContext(ctx, createPropertyMedia, arg.PropertyID, arg.Url, arg.Type)
	var i PropertyMedium
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.Url,
		&i.Type,
	)
	return i, err
}

const deleteAllPropertyAmenity = `-- name: DeleteAllPropertyAmenity :exec
DELETE FROM property_amenity WHERE property_id = $1
`

func (q *Queries) DeleteAllPropertyAmenity(ctx context.Context, propertyID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAllPropertyAmenity, propertyID)
	return err
}

const deleteAllPropertyFeature = `-- name: DeleteAllPropertyFeature :exec
DELETE FROM property_feature WHERE property_id = $1
`

func (q *Queries) DeleteAllPropertyFeature(ctx context.Context, propertyID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAllPropertyFeature, propertyID)
	return err
}

const deleteAllPropertyMedia = `-- name: DeleteAllPropertyMedia :exec
DELETE FROM property_media WHERE property_id = $1
`

func (q *Queries) DeleteAllPropertyMedia(ctx context.Context, propertyID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAllPropertyMedia, propertyID)
	return err
}

const deleteAllPropertyTag = `-- name: DeleteAllPropertyTag :exec
DELETE FROM property_tag WHERE property_id = $1
`

func (q *Queries) DeleteAllPropertyTag(ctx context.Context, propertyID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAllPropertyTag, propertyID)
	return err
}

const deleteProperty = `-- name: DeleteProperty :exec
DELETE FROM properties WHERE id = $1
`

func (q *Queries) DeleteProperty(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProperty, id)
	return err
}

const getAllPropertyAmenities = `-- name: GetAllPropertyAmenities :many
SELECT id, amenity FROM p_amenities
`

func (q *Queries) GetAllPropertyAmenities(ctx context.Context) ([]PAmenity, error) {
	rows, err := q.db.QueryContext(ctx, getAllPropertyAmenities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PAmenity
	for rows.Next() {
		var i PAmenity
		if err := rows.Scan(&i.ID, &i.Amenity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPropertyFeatures = `-- name: GetAllPropertyFeatures :many
SELECT id, feature FROM p_features
`

func (q *Queries) GetAllPropertyFeatures(ctx context.Context) ([]PFeature, error) {
	rows, err := q.db.QueryContext(ctx, getAllPropertyFeatures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PFeature
	for rows.Next() {
		var i PFeature
		if err := rows.Scan(&i.ID, &i.Feature); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPropertiesByOwnerId = `-- name: GetPropertiesByOwnerId :many
SELECT id, owner_id, name, area, number_of_floors, year_built, orientation, full_address, district, city, lat, lng, type, created_at, updated_at FROM properties WHERE owner_id = $1 LIMIT $2 OFFSET $3
`

type GetPropertiesByOwnerIdParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) GetPropertiesByOwnerId(ctx context.Context, arg GetPropertiesByOwnerIdParams) ([]Property, error) {
	rows, err := q.db.QueryContext(ctx, getPropertiesByOwnerId, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Property
	for rows.Next() {
		var i Property
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Area,
			&i.NumberOfFloors,
			&i.YearBuilt,
			&i.Orientation,
			&i.FullAddress,
			&i.District,
			&i.City,
			&i.Lat,
			&i.Lng,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPropertyAmenities = `-- name: GetPropertyAmenities :many
SELECT property_id, amenity_id, description FROM property_amenity WHERE property_id = $1
`

func (q *Queries) GetPropertyAmenities(ctx context.Context, propertyID uuid.UUID) ([]PropertyAmenity, error) {
	rows, err := q.db.QueryContext(ctx, getPropertyAmenities, propertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PropertyAmenity
	for rows.Next() {
		var i PropertyAmenity
		if err := rows.Scan(&i.PropertyID, &i.AmenityID, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPropertyById = `-- name: GetPropertyById :one
SELECT id, owner_id, name, area, number_of_floors, year_built, orientation, full_address, district, city, lat, lng, type, created_at, updated_at FROM properties WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPropertyById(ctx context.Context, id uuid.UUID) (Property, error) {
	row := q.db.QueryRowContext(ctx, getPropertyById, id)
	var i Property
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Area,
		&i.NumberOfFloors,
		&i.YearBuilt,
		&i.Orientation,
		&i.FullAddress,
		&i.District,
		&i.City,
		&i.Lat,
		&i.Lng,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPropertyFeatures = `-- name: GetPropertyFeatures :many
SELECT property_id, feature_id, description FROM property_feature WHERE property_id = $1
`

func (q *Queries) GetPropertyFeatures(ctx context.Context, propertyID uuid.UUID) ([]PropertyFeature, error) {
	rows, err := q.db.QueryContext(ctx, getPropertyFeatures, propertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PropertyFeature
	for rows.Next() {
		var i PropertyFeature
		if err := rows.Scan(&i.PropertyID, &i.FeatureID, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPropertyMedium = `-- name: GetPropertyMedium :many
SELECT id, property_id, url, type FROM property_media WHERE property_id = $1
`

func (q *Queries) GetPropertyMedium(ctx context.Context, propertyID uuid.UUID) ([]PropertyMedium, error) {
	rows, err := q.db.QueryContext(ctx, getPropertyMedium, propertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PropertyMedium
	for rows.Next() {
		var i PropertyMedium
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.Url,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPropertyTags = `-- name: GetPropertyTags :many
SELECT id, property_id, tag FROM property_tag WHERE property_id = $1
`

func (q *Queries) GetPropertyTags(ctx context.Context, propertyID uuid.UUID) ([]PropertyTag, error) {
	rows, err := q.db.QueryContext(ctx, getPropertyTags, propertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PropertyTag
	for rows.Next() {
		var i PropertyTag
		if err := rows.Scan(&i.ID, &i.PropertyID, &i.Tag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProperty = `-- name: UpdateProperty :exec
UPDATE properties SET
  name = coalesce($2, name),
  area = coalesce($3, area),
  number_of_floors = coalesce($4, number_of_floors),
  year_built = coalesce($5, year_built),
  orientation = coalesce($6, orientation),
  full_address = coalesce($7, full_address),
  district = coalesce($8, district),
  city = coalesce($9, city),
  lat = coalesce($10, lat),
  lng = coalesce($11, lng),
  updated_at = NOW()
WHERE id = $1
`

type UpdatePropertyParams struct {
	ID             uuid.UUID       `json:"id"`
	Name           sql.NullString  `json:"name"`
	Area           sql.NullFloat64 `json:"area"`
	NumberOfFloors sql.NullInt32   `json:"number_of_floors"`
	YearBuilt      sql.NullInt32   `json:"year_built"`
	Orientation    sql.NullString  `json:"orientation"`
	FullAddress    sql.NullString  `json:"full_address"`
	District       sql.NullString  `json:"district"`
	City           sql.NullString  `json:"city"`
	Lat            sql.NullFloat64 `json:"lat"`
	Lng            sql.NullFloat64 `json:"lng"`
}

func (q *Queries) UpdateProperty(ctx context.Context, arg UpdatePropertyParams) error {
	_, err := q.db.ExecContext(ctx, updateProperty,
		arg.ID,
		arg.Name,
		arg.Area,
		arg.NumberOfFloors,
		arg.YearBuilt,
		arg.Orientation,
		arg.FullAddress,
		arg.District,
		arg.City,
		arg.Lat,
		arg.Lng,
	)
	return err
}
