// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
