// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CheckApplicationUpdatabilty(ctx context.Context, arg CheckApplicationUpdatabiltyParams) (bool, error)
	CheckApplicationVisibility(ctx context.Context, arg CheckApplicationVisibilityParams) (bool, error)
	CheckListingExpired(ctx context.Context, id uuid.UUID) (pgtype.Bool, error)
	CheckListingOwnership(ctx context.Context, arg CheckListingOwnershipParams) (int64, error)
	CheckMsgGroupMembership(ctx context.Context, arg CheckMsgGroupMembershipParams) (bool, error)
	CheckUnitManageability(ctx context.Context, arg CheckUnitManageabilityParams) (int64, error)
	CheckUnitOfProperty(ctx context.Context, arg CheckUnitOfPropertyParams) (int64, error)
	CheckValidUnitForListing(ctx context.Context, arg CheckValidUnitForListingParams) (int64, error)
	CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error)
	CreateApplicationCoap(ctx context.Context, arg CreateApplicationCoapParams) (ApplicationCoap, error)
	CreateApplicationMinor(ctx context.Context, arg CreateApplicationMinorParams) (ApplicationMinor, error)
	CreateApplicationPet(ctx context.Context, arg CreateApplicationPetParams) (ApplicationPet, error)
	CreateApplicationVehicle(ctx context.Context, arg CreateApplicationVehicleParams) (ApplicationVehicle, error)
	CreateListing(ctx context.Context, arg CreateListingParams) (Listing, error)
	CreateListingPolicy(ctx context.Context, arg CreateListingPolicyParams) (ListingPolicy, error)
	CreateListingTag(ctx context.Context, arg CreateListingTagParams) (ListingTag, error)
	CreateListingUnit(ctx context.Context, arg CreateListingUnitParams) (ListingUnit, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateMsgGroup(ctx context.Context, arg CreateMsgGroupParams) (MsgGroup, error)
	CreateMsgGroupMember(ctx context.Context, arg CreateMsgGroupMemberParams) (MsgGroupMember, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreatePaymentItem(ctx context.Context, arg CreatePaymentItemParams) (PaymentItem, error)
	CreatePreRental(ctx context.Context, arg CreatePreRentalParams) (Prerental, error)
	CreatePreRentalCoap(ctx context.Context, arg CreatePreRentalCoapParams) (PrerentalCoap, error)
	CreateProperty(ctx context.Context, arg CreatePropertyParams) (Property, error)
	CreatePropertyFeature(ctx context.Context, arg CreatePropertyFeatureParams) (PropertyFeature, error)
	CreatePropertyManager(ctx context.Context, arg CreatePropertyManagerParams) (PropertyManager, error)
	CreatePropertyMedia(ctx context.Context, arg CreatePropertyMediaParams) (PropertyMedium, error)
	CreatePropertyTag(ctx context.Context, arg CreatePropertyTagParams) (PropertyTag, error)
	CreateReminder(ctx context.Context, arg CreateReminderParams) (Reminder, error)
	CreateReminderMember(ctx context.Context, arg CreateReminderMemberParams) (ReminderMember, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUnit(ctx context.Context, arg CreateUnitParams) (Unit, error)
	CreateUnitAmenity(ctx context.Context, arg CreateUnitAmenityParams) (UnitAmenity, error)
	CreateUnitMedia(ctx context.Context, arg CreateUnitMediaParams) (UnitMedium, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteApplication(ctx context.Context, id int64) error
	DeleteListing(ctx context.Context, id uuid.UUID) error
	DeleteMsgGroup(ctx context.Context, groupID int64) error
	DeleteMsgGroupMember(ctx context.Context, arg DeleteMsgGroupMemberParams) error
	DeletePayment(ctx context.Context, id int64) error
	DeletePreRental(ctx context.Context, id int64) error
	DeleteProperty(ctx context.Context, id uuid.UUID) error
	DeletePropertyFeature(ctx context.Context, arg DeletePropertyFeatureParams) error
	DeletePropertyManager(ctx context.Context, arg DeletePropertyManagerParams) error
	DeletePropertyMedia(ctx context.Context, arg DeletePropertyMediaParams) error
	DeletePropertyTag(ctx context.Context, arg DeletePropertyTagParams) error
	DeleteReminder(ctx context.Context, id int64) error
	DeleteUnit(ctx context.Context, id uuid.UUID) error
	DeleteUnitAmenity(ctx context.Context, arg DeleteUnitAmenityParams) error
	DeleteUnitMedia(ctx context.Context, arg DeleteUnitMediaParams) error
	GetAllPropertyFeatures(ctx context.Context) ([]PFeature, error)
	GetAllRentalPolicies(ctx context.Context) ([]RentalPolicy, error)
	GetAllUnitAmenities(ctx context.Context) ([]UAmenity, error)
	GetApplicationByID(ctx context.Context, id int64) (Application, error)
	GetApplicationCoaps(ctx context.Context, applicationID int64) ([]ApplicationCoap, error)
	GetApplicationMinors(ctx context.Context, applicationID int64) ([]ApplicationMinor, error)
	GetApplicationPets(ctx context.Context, applicationID int64) ([]ApplicationPet, error)
	GetApplicationVehicles(ctx context.Context, applicationID int64) ([]ApplicationVehicle, error)
	GetApplicationsByUserId(ctx context.Context, arg GetApplicationsByUserIdParams) ([]int64, error)
	GetApplicationsOfListing(ctx context.Context, listingID uuid.UUID) ([]int64, error)
	GetApplicationsToUser(ctx context.Context, arg GetApplicationsToUserParams) ([]int64, error)
	GetListingByID(ctx context.Context, id uuid.UUID) (Listing, error)
	GetListingPolicies(ctx context.Context, listingID uuid.UUID) ([]ListingPolicy, error)
	GetListingTags(ctx context.Context, listingID uuid.UUID) ([]ListingTag, error)
	GetListingUnits(ctx context.Context, listingID uuid.UUID) ([]ListingUnit, error)
	// Get expired / active listings
	GetListingsOfProperty(ctx context.Context, arg GetListingsOfPropertyParams) ([]uuid.UUID, error)
	GetManagedProperties(ctx context.Context, managerID uuid.UUID) ([]GetManagedPropertiesRow, error)
	GetMessagesOfGroup(ctx context.Context, arg GetMessagesOfGroupParams) ([]Message, error)
	GetMsgGroup(ctx context.Context, groupID int64) (MsgGroup, error)
	GetMsgGroupByName(ctx context.Context, arg GetMsgGroupByNameParams) (MsgGroup, error)
	GetMsgGroupMembers(ctx context.Context, groupID int64) ([]GetMsgGroupMembersRow, error)
	GetPaymentById(ctx context.Context, id int64) (Payment, error)
	GetPaymentItemsByPaymentId(ctx context.Context, paymentID int64) ([]PaymentItem, error)
	GetPreRental(ctx context.Context, id int64) (Prerental, error)
	GetPreRentalCoapByPreRentalID(ctx context.Context, prerentalID int64) ([]PrerentalCoap, error)
	GetPreRentalContract(ctx context.Context, id int64) (GetPreRentalContractRow, error)
	GetPropertyById(ctx context.Context, id uuid.UUID) (Property, error)
	GetPropertyFeatures(ctx context.Context, propertyID uuid.UUID) ([]PropertyFeature, error)
	GetPropertyManagers(ctx context.Context, propertyID uuid.UUID) ([]PropertyManager, error)
	GetPropertyMedia(ctx context.Context, propertyID uuid.UUID) ([]PropertyMedium, error)
	GetPropertyTags(ctx context.Context, propertyID uuid.UUID) ([]PropertyTag, error)
	GetReminderById(ctx context.Context, id int64) (Reminder, error)
	GetReminderMembers(ctx context.Context, reminderID int64) ([]uuid.UUID, error)
	GetRemindersByCreator(ctx context.Context, creatorID uuid.UUID) ([]Reminder, error)
	GetRemindersOfUser(ctx context.Context, userID uuid.UUID) ([]Reminder, error)
	GetRemindersOfUserWithResourceTag(ctx context.Context, arg GetRemindersOfUserWithResourceTagParams) ([]Reminder, error)
	GetSessionById(ctx context.Context, id uuid.UUID) (Session, error)
	GetUnitAmenities(ctx context.Context, unitID uuid.UUID) ([]UnitAmenity, error)
	GetUnitById(ctx context.Context, id uuid.UUID) (Unit, error)
	GetUnitManagers(ctx context.Context, id uuid.UUID) ([]PropertyManager, error)
	GetUnitMedia(ctx context.Context, unitID uuid.UUID) ([]UnitMedium, error)
	GetUnitsOfProperty(ctx context.Context, propertyID uuid.UUID) ([]Unit, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	IsPropertyPublic(ctx context.Context, id uuid.UUID) (bool, error)
	IsUnitPublic(ctx context.Context, id uuid.UUID) (bool, error)
	UpdateApplicationStatus(ctx context.Context, arg UpdateApplicationStatusParams) ([]int64, error)
	UpdateListing(ctx context.Context, arg UpdateListingParams) error
	UpdateListingStatus(ctx context.Context, arg UpdateListingStatusParams) error
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) ([]int64, error)
	UpdatePayment(ctx context.Context, arg UpdatePaymentParams) error
	UpdatePreRental(ctx context.Context, arg UpdatePreRentalParams) error
	UpdatePreRentalContract(ctx context.Context, arg UpdatePreRentalContractParams) error
	UpdateProperty(ctx context.Context, arg UpdatePropertyParams) error
	UpdateReminder(ctx context.Context, arg UpdateReminderParams) ([]Reminder, error)
	UpdateSessionBlockingStatus(ctx context.Context, arg UpdateSessionBlockingStatusParams) error
	UpdateUnit(ctx context.Context, arg UpdateUnitParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
