root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # Add additional arguments when running binary
  args_bin = []
  # Binary file yields from `cmd`.
  bin = "./tmp/main"
  # Just plain old shell command. You could use `make` as well.
  cmd = "go build -o ./tmp/main ."
  # It's not necessary to trigger build each time file changes if it's too frequent.
  delay = 500 # ms
  # Watch these directories if you specified.
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "db_data", ".idea", ".vscode", "internal/infrastructure/database/migrations", "internal/infrastructure/database/queries"]
  # Exclude files.
  exclude_file = []
  # Exclude specific regular expressions.
  exclude_regex = ["_test.go"]
  # Exclude unchanged files.
  exclude_unchanged = true
  # Follow symlink for directories
  follow_symlink = true
  full_bin = ""
  # Watch these directories if you specified.
  include_dir = []
  # Watch these filename extensions.
  include_ext = ["go", "tpl", "tmpl", "html"]
  # Watch these files.
  include_file = []
  # Delay after sending Interrupt signal
  kill_delay = 500 # nanosecond
  # This log file places in your tmp_dir.
  log = "air.log"
  # Poll files for changes instead of using fsnotify.
  poll = false
  # Poll interval (defaults to the minimum interval of 500ms).
  poll_interval = 500 # ms
  # Array of commands to run after ^C
  post_cmd = []
  # Array of commands to run before each build
  pre_cmd = []
  # Rerun binary or not
  rerun = false
  # Delay after each execution
  rerun_delay = 500
  # Send Interrupt signal before killing process (windows does not support this feature)
  send_interrupt = true
  # Stop running old binary when build errors occur.
  stop_on_error = true

[color]
# Customize each part's color. If no color found, use the raw app log.
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
# Show log time
  time = false
# Only show main log (silences watcher, build, runner)
  main_only = false

[misc]
  # Delete tmp directory on exit
  clean_on_exit = true

# [proxy]
#   app_port = 0
#   enabled = false
#   proxy_port = 0

[screen]
  clear_on_rebuild = true
  keep_scroll = true
