version: '3.7'
services:
  postgresd:
    container_name: rrmsdb
    image: postgres:15.2
    ports:
      - 32755:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: rrms
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d rrms -U root" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - intranet
  asynq_redis:
    container_name: rrms_asynq_redis
    image: redis:7.2.4-alpine
    ports:
      - 32756:6379
    networks:
      - intranet
networks:
  intranet:
    name: rrms_network
